- trade_license/admin.py
- trade_license/apps.py
- trade_license/helpers.py
- trade_license/models.py
- trade_license/serializers.py
- trade_license/tests.py
- trade_license/urls.py
- trade_license/views.py
added Trade License Module to the exiting Tara project
> Add Trade License

- invoicing/models.py
- invoicing/serializers.py
- invoicing/views.py
- usermanagement/roles_views.py
- usermanagement/serializers.py
- usermanagement/urls.py
refactor invoicing profile management and add context roles endpoint
> refactor invoicing profile management and add context roles endpoint

- usermanagement/login_api.py
add business_id to user context response in login API
> add business_id to user context response in login API

- usermanagement/feature_views.py
> retsructed the module id case 

- invoicing/serializers.py
add BusinessSerializer to handle Business model serialization
> add BusinessSerializer to handle Business model serialization

- invoicing/views.py
refactor invoice view to improve attribute access for business details
> refactor invoice view to improve attribute access for business details

- payroll/views.py
add success status to employee deletion response
> add success status to employee deletion response

- usermanagement/switch_context.py
add user context roles and related information to switch context response
> add user context roles and related information to switch context response

- usermanagement/payment_webhooks.py
add logging to razorpay webhook for better debugging and error handling
> add logging to razorpay webhook for better debugging and error handling

- usermanagement/payment_webhooks.py
add permission classes to razorpay webhook for enhanced security
> add permission classes to razorpay webhook for enhanced security

- usermanagement/payment_webhooks.py
update webhook secret in razorpay webhook for testing purposes
> update webhook secret in razorpay webhook for testing purposes

- usermanagement/switch_context.py
refactor switch context to improve variable naming for clarity
> refactor switch context to improve variable naming for clarity

- usermanagement/payment_webhooks.py
feat: enhance payment information handling in payment_webhooks.py
> feat: enhance payment information handling in payment_webhooks.py

- usermanagement/models.py
feat: implement payment success handling for module subscriptions
> feat: implement payment success handling for module subscriptions

- usermanagement/helpers.py
- usermanagement/models.py
- usermanagement/other_factors.py
- usermanagement/serializers.py
- usermanagement/urls.py
feat: add TDS, License, DSC, Bank, and KMP details models and serializers; implement related API endpoints
> feat: add TDS, License, DSC, Bank, and KMP details models and serializers; implement related API endpoints

- usermanagement/other_factors.py
- usermanagement/serializers.py
refactor: simplify GST, TDS, License, DSC, Bank, and KMP detail endpoints;
> refactor: simplify GST, TDS, License, DSC, Bank, and KMP detail endpoints;

- usermanagement/other_factors.py
refactor: update detail retrieval logic for GST, TDS, License, DSC, Bank, and KMP endpoints to handle multiple records and improve error handling
> refactor: update detail retrieval logic for GST, TDS, License, DSC, Bank, and KMP endpoints to handle multiple records and improve error handling

- usermanagement/other_factors.py
refactor: enhance error handling for detail retrieval in GST, TDS, License, DSC, and Bank endpoints
> refactor: enhance error handling for detail retrieval in GST, TDS, License, DSC, and Bank endpoints

- payroll/views.py
[signation creation endpoints](refactor: improve error handling in work location, department, and designation creation endpoints)
> refactor: improve error handling in work location, department, and designation creation endpoints

- payroll/views.py
refactor: update financial year and month handling in new employees list endpoint
> refactor: update financial year and month handling in new employees list endpoint

- usermanagement/context_business_subscription.py
- usermanagement/models.py
feat: add MSME registration fields and validation to business model and subscription context
> feat: add MSME registration fields and validation to business model and subscription context

- usermanagement/other_factors.py
refactor: streamline bank detail retrieval by removing redundant error handling
> refactor: streamline bank detail retrieval by removing redundant error handling

- usermanagement/views.py
refactor: simplify is_active parameter handling in module filters
> refactor: simplify is_active parameter handling in module filters

- usermanagement/views.py
feat: add category filter to module retrieval in views
> feat: add category filter to module retrieval in views

- invoicing/views.py
refactor: remove unnecessary permission requirement for createDocument endpoint
> refactor: remove unnecessary permission requirement for createDocument endpoint

- Tara/templates/invoice.html
- invoicing/models.py
- invoicing/serializers.py
- invoicing/views.py
feat: add customer GSTIN and PAN fields to invoice model, template and serializer
> feat: add customer GSTIN and PAN fields to invoice model, template and serializer

- usermanagement/other_factors.py
refactor: fix user detail retrieval by changing primary key lookup to user field
> refactor: fix user detail retrieval by changing primary key lookup to user field

- Tara/templates/invoice.html
- invoicing/views.py
- usermanagement/serializers.py
feat: enhance invoice template with additional fields and conditional display for terms and conditions
> feat: enhance invoice template with additional fields and conditional display for terms and conditions

- usermanagement/other_factors.py
- usermanagement/urls.py
feat: add user detail endpoint for retrieving, updating, and deleting users
> feat: add user detail endpoint for retrieving, updating, and deleting users

- Tara/templates/salary_template.html
- payroll/views.py
feat: add conditional display for EPF, ESI, and PT in salary template
> feat: add conditional display for EPF, ESI, and PT in salary template

- usermanagement/service_views.py
feat: add AllowAny permission class to service and service plan endpoints
> feat: add AllowAny permission class to service and service plan endpoints

- usermanagement/other_factors.py
fix: update error messages for password change validation
> fix: update error messages for password change validation

- payroll/helpers.py
- payroll/models.py
- payroll/views.py
feat: change logo field to FileField and refactor logo upload handling in PayrollOrg and implement logo upload functionality for PayrollOrg model
> feat: change logo field to FileField and refactor logo upload handling in PayrollOrg and implement logo upload functionality for PayrollOrg model

- usermanagement/context_business_subscription.py
- usermanagement/models.py
- usermanagement/service_serializers.py
- usermanagement/service_views.py
- usermanagement/urls.py
feat: add endpoints to retrieve module subscriptions and service requests by context
> feat: add endpoints to retrieve module subscriptions and service requests by context

- usermanagement/context_business_subscription.py
- usermanagement/service_views.py
- usermanagement/urls.py
> feat: update context service request and module subscription endpoints to use path parameters

- company_incorporation/models.py
- usermanagement/login_api.py
- usermanagement/models.py
Restructured few things to handle special case for the SuperUser
> Restructured few things to handle special case for the SuperUser

- payroll/views.py
feat: refactor PayrollOrg logo handling to support file uploads and improve data validation
> feat: refactor PayrollOrg logo handling to support file uploads and improve data validation

- payroll/views.py
feat: enhance error handling in PayrollOrg creation and update process****
> feat: enhance error handling in PayrollOrg creation and update process

- nginx/nginx.conf
feat: set client_max_body_size to 20MB for improved file upload handling
> feat: set client_max_body_size to 20MB for improved file upload handling

- usermanagement/service_views.py
- usermanagement/urls.py
feat: add endpoint to retrieve services by type with validation for context type
> feat: add endpoint to retrieve services by type with validation for context type

- payroll/views.py
feat: create a mutable copy of request data in post method for logo handling
> feat: create a mutable copy of request data in post method for logo handling

- payroll/models.py
feat: add filling_address_location_name field to models for default address handling
> feat: add filling_address_location_name field to models for default address handling

- Tara/settings/default.py
feat: update database credentials for production environment
> feat: update database credentials for production environment

- usermanagement/models.py
- usermanagement/service_payment.py
feat: update models and service payment logic to include context and added_by fields
> feat: update models and service payment logic to include context and added_by fields

- usermanagement/create_service_request.py
feat: enhance service request creation with Razorpay integration and validation checks
> feat: enhance service request creation with Razorpay integration and validation checks

- usermanagement/create_service_request.py
feat: update service request creation to include plan ID and context ID
> feat: update service request creation to include plan ID and context ID

- Tara/templates/salary_template.html
feat: add conditional display for income tax and loan EMI in salary template
> feat: add conditional display for income tax and loan EMI in salary template

- usermanagement/service_registration_process.py
feat: simplify role assignment logic in service registration process
> feat: simplify role assignment logic in service registration process

- usermanagement/business_registration_api.py
- usermanagement/service_registration_process.py
> Production Push 08-05-2025

- payroll/views.py
feat: refine EPF and ESI enabled checks for payroll organization
> feat: refine EPF and ESI enabled checks for payroll organization

- usermanagement/other_factors.py
- usermanagement/serializers.py
feat: update GSTDetails handling to conditionally remove gst_document from requests
> feat: update GSTDetails handling to conditionally remove gst_document from requests

- payroll/views.py
feat: refactor EPF and ESI enabled checks for payroll organization
> feat: refactor EPF and ESI enabled checks for payroll organization

- payroll/helpers.py
- usermanagement/models.py
> Code Push 08-05-2025

- payroll/views.py
feat: enhance active employee filtering to include date of joining check
> feat: enhance active employee filtering to include date of joining check

- payroll/models.py
- payroll/serializers.py
- payroll/views.py
feat: remove validation for minimum selected days in pay schedule
> feat: remove validation for minimum selected days in pay schedule

- invoicing/urls.py
feat: update URL path for customer profile update endpoint
> feat: update URL path for customer profile update endpoint

- payroll/views.py
- usermanagement/other_factors.py
- usermanagement/urls.py
feat: optimize data handling by removing unnecessary copy of request data and add endpoints to list contacts and consultations
> feat: optimize data handling by removing unnecessary copy of request data and add endpoints to list contacts and consultations

- payroll/views.py
feat: optimize logo handling in request data by conditionally using mutable copy
> feat: optimize logo handling in request data by conditionally using mutable copy

- usermanagement/serializers.py
feat: update AddressSerializer to allow null and blank values for address_line2
> feat: update AddressSerializer to allow null and blank values for address_line2

- payroll/views.py
feat: ensure numeric handling for monthly benefits and deductions in salary calculations
> feat: ensure numeric handling for monthly benefits and deductions in salary calculations

- usermanagement/models.py
- usermanagement/other_factors.py
- usermanagement/urls.py
feat: add status field to Contact and Consultation models and implement detail endpoints
> feat: add status field to Contact and Consultation models and implement detail endpoints

- docwallet/urls.py
- docwallet/views.py
> Code Push 12-05-2025

- usermanagement/urls.py
- usermanagement/views.py
feat: add happy_coder endpoint to return a cheerful message
> feat: add happy_coder endpoint to return a cheerful message

- payroll/views.py
feat: update payroll assignment to use payroll_id in record processing
> feat: update payroll assignment to use payroll_id in record processing

- usermanagement/tests.py
feat: update test file to include API testing comments
> feat: update test file to include API testing comments

- usermanagement/add_team_business.py
- usermanagement/other_factors.py
- usermanagement/serializers.py
> feat: enhance user creation validation and allow partial updates for user details

- invoicing/models.py
- invoicing/serializers.py
- invoicing/views.py
feat: enhance InvoiceFormat model with additional fields and update invoice number generation logic
> feat: enhance InvoiceFormat model with additional fields and update invoice number generation logic

- invoicing/models.py
- invoicing/views.py
- usermanagement/models.py
- usermanagement/other_factors.py
- usermanagement/serializers.py
- usermanagement/urls.py
feat: add Branch model and related API endpoints for managing business branches and rename invoice_format related name
> feat: add Branch model and related API endpoints for managing business branches and rename invoice_format related name

- invoicing/serializers.py
feat: refactor InvoiceFormatSerializer and update invoicing profile to use nested serializer for invoice formats
> feat: refactor InvoiceFormatSerializer and update invoicing profile to use nested serializer for invoice formats

- invoicing/models.py
- invoicing/views.py
feat: update is_common_format field to use CharField for better clarity and handling
> feat: update is_common_format field to use CharField for better clarity and handling

- invoicing/views.py
feat: update views to retrieve gstin and branch_code from query parameters for improved API consistency
> feat: update views to retrieve gstin and branch_code from query parameters for improved API consistency

- usermanagement/login_api.py
feat: remove is_super_user field from user response in login API
> feat: remove is_super_user field from user response in login API

- usermanagement/add_team_business.py
feat: update user status logic to handle multiple pending conditions in registration flow
> feat: update user status logic to handle multiple pending conditions

- invoicing/serializers.py
feat: update branch_code field in serializers to allow blank values for improved data handling
> feat: update branch_code field in serializers to allow blank values for improved data handling

- usermanagement/models.py
- usermanagement/serializers.py
feat: add is_super_admin field to models and update read_only_fields in serializers for enhanced user management
> feat: add is_super_admin field to models and update read_only_fields in serializers for enhanced user management

- invoicing/helpers.py
- invoicing/models.py
- payroll/models.py
- payroll/views.py
- usermanagement/helpers.py
- usermanagement/models.py
- usermanagement/other_factors.py
- usermanagement/serializers.py
- usermanagement/urls.py
feat: implement business logo upload functionality with associated model and serializer
> feat: implement business logo upload functionality with associated model and serializer

- usermanagement/add_team_business.py
feat: add is_super_admin field to user creation in add_team_business.py
> feat: add is_super_admin field to user creation in add_team_business.py

- usermanagement/add_team_business.py
feat: update user status logic to include 'standard' registration flow
> feat: update user status logic to include 'standard' registration flow

- usermanagement/business_registration_api.py
- usermanagement/login_api.py
- usermanagement/service_registration_process.py
- usermanagement/standard_registration.py
feat: include is_platform_context in login API response for enhanced context visibility
> feat: include is_platform_context in login API response for enhanced context visibility

- labour_license/helpers.py
- labour_license/models.py
- labour_license/serializers.py
- labour_license/views.py
- servicetasks/serializers.py
- servicetasks/views.py
- usermanagement/create_service_request.py
- usermanagement/helpers.py
feat: enhance service request handling with due date assignment and address field updates
> feat: enhance service request handling with due date assignment and address field updates

- usermanagement/service_serializers.py
feat: add UserDisplaySerializer for full name representation in service requests
> feat: add UserDisplaySerializer for full name representation in service requests

- servicetasks/urls.py
- servicetasks/views.py
feat: add endpoint to retrieve service tasks by service request ID
> feat: add endpoint to retrieve service tasks by service request ID

- Tara/settings/default.py
- Tara/urls.py
- income_tax_returns/admin.py
- income_tax_returns/apps.py
- income_tax_returns/dividend_views.py
- income_tax_returns/family_pension_views.py
- income_tax_returns/gift_income_views.py
- income_tax_returns/helpers.py
- income_tax_returns/house_property_income_views.py
- income_tax_returns/interest_income_views.py
- income_tax_returns/models.py
- income_tax_returns/nri_views.py
- income_tax_returns/other_income_views.py
- income_tax_returns/salary_income_views.py
- income_tax_returns/serializers.py
- income_tax_returns/tax_paid_details_views.py
- income_tax_returns/tests.py
- income_tax_returns/urls.py
- income_tax_returns/views.py
- usermanagement/add_team_business.py
> Added Income Returns Files

- usermanagement/models.py
- usermanagement/service_serializers.py
feat: add label field to Service model for enhanced data representation
> feat: add label field to Service model for enhanced data representation

- income_tax_returns/dividend_views.py
- income_tax_returns/family_pension_views.py
- income_tax_returns/gift_income_views.py
- income_tax_returns/helpers.py
- income_tax_returns/house_property_income_views.py
- income_tax_returns/interest_income_views.py
- income_tax_returns/models.py
- income_tax_returns/other_income_views.py
- income_tax_returns/salary_income_views.py
- income_tax_returns/serializers.py
- income_tax_returns/urls.py
- income_tax_returns/views.py
- labour_license/helpers.py
- labour_license/models.py
- labour_license/views.py
Update the helpers functions in itr
> Update the helpers functions in itr

- income_tax_returns/family_pension_views.py
- income_tax_returns/models.py
- income_tax_returns/section_80d_views.py
- income_tax_returns/serializers.py
- income_tax_returns/views.py
Remodifed the code as per the new changes in Income tax Returns
> Remodifed the code as per the new changes in Income tax Returns

- trade_license/models.py
Refactor: Add one more field additional_space in BusinessLocation Model
> Refactor: Add one more field additional_space in BusinessLocation Model

- income_tax_returns/models.py
- income_tax_returns/views.py
Income Tax Returns Few Code Changes as per the Request
> Income Tax Returns Few Code Changes as per the Request

- usermanagement/helpers.py
Refactor: add itr-filing section with relevant fields in helpers
> Refactor: add itr-filing section with relevant fields in helpers

- income_tax_returns/views.py
Refactor: update client reference in service request handling
> Refactor: update client reference in service request handling

- income_tax_returns/helpers.py
- income_tax_returns/models.py
- labour_license/models.py
- msme_registration/serializers.py
- msme_registration/urls.py
- msme_registration/views.py
- trade_license/helpers.py
Refactor: Itr models, helpers and add get api endpoint in msme to retrieve full details
> Refactor: Itr models, helpers and add get api endpoint in msme to retrieve full details

- income_tax_returns/urls.py
Testing the Income Tax returns Case
> Testing the Income Tax returns Case

- income_tax_returns/helpers.py
- income_tax_returns/urls.py
- income_tax_returns/views.py
Remodified Few cases As per the Incoem tax returns
> Remodified Few cases As per the Incoem tax returns

- income_tax_returns/serializers.py
**remodified few cases as per new cases**
> remodified few cases as per new cases

- payroll/models.py
- payroll/serializers.py
Refactor EmployeeSalaryDetails: convert employee to OneToOneField, add updated_on, and add UAN validation in serializer
> Refactor EmployeeSalaryDetails: convert employee to OneToOneField, add updated_on, and add UAN validation in serializer

- payroll/helpers.py
- payroll/models.py
- payroll/urls.py
- payroll/views.py
> tds calculation

- income_tax_returns/house_property_income_views.py
- income_tax_returns/nri_views.py
- income_tax_returns/serializers.py
feat: enhance NRIEmployeeSalaryDetails handling with employment_history JSON parsing and optional ID support
> feat: enhance NRIEmployeeSalaryDetails handling with employment_history JSON parsing and optional ID support

- payroll/serializers.py
feat: add employee field to EmployeeSalaryHistorySerializer for improved data structure
> feat: add employee field to EmployeeSalaryHistorySerializer for improved data structure

- income_tax_returns/nri_views.py
- payroll/serializers.py
- payroll/views.py
feat: add associate_id field to EmployeeSalaryHistorySerializer for improved employee data representation
> feat: add associate_id field to EmployeeSalaryHistorySerializer for improved employee data representation

- payroll/serializers.py
- payroll/views.py
feat: refactor EmployeeSalaryHistorySerializer and update views for improved employee data handling
> feat: refactor EmployeeSalaryHistorySerializer and update views for improved employee data handling

- income_tax_returns/agriculture_income.py
- income_tax_returns/dividend_views.py
- income_tax_returns/family_pension_views.py
- income_tax_returns/foreign_income_views.py
- income_tax_returns/gift_income_views.py
- income_tax_returns/winning_income_views.py
feat: update income views to return serializer data instead of success messages for improved response consistency
> feat: update income views to return serializer data instead of success messages for improved response consistency

- income_tax_returns/business_professional_income_views.py
feat: update business_professional_income_upsert to handle opting_data as JSON string
> feat: update business_professional_income_upsert to handle opting_data as JSON string

- income_tax_returns/business_professional_income_views.py
- income_tax_returns/models.py
feat: enhance business professional income upsert to support additional file types and improve request handling
> feat: enhance business professional income upsert to support additional file types and improve request handling

- income_tax_returns/capital_gains_funds_details_views.py
- income_tax_returns/capital_gains_views.py
- income_tax_returns/deductions.py
- income_tax_returns/serializers.py
feat: update JSON handling for investment types and reinvestment details in capital gains views
> feat: update JSON handling for investment types and reinvestment details in capital gains views

- income_tax_returns/capital_gains_views.py
feat: update capital gains view response to include serialized data on successful property addition
> feat: update capital gains view response to include serialized data on successful property addition

- payroll/views.py
feat: standardize status values in payroll processing logic to improve consistency
> feat: standardize status values in payroll processing logic to improve consistency

- income_tax_returns/section_80g_views.py
- income_tax_returns/serializers.py
feat: include serializer data in response for Section 80G donation creation and correct section_80ettattbu reference
> feat: include serializer data in response for Section 80G donation creation and correct section_80ettattbu reference

- income_tax_returns/helpers.py
- income_tax_returns/models.py
feat: correct service request ID reference in section 80ee file handling and update foreign key relationship in Section80DDBDocuments
> feat: correct service request ID reference in section 80ee file handling and update foreign key relationship in Section80DDBDocuments

- income_tax_returns/helpers.py
- income_tax_returns/models.py
- income_tax_returns/section_80c_views.py
- income_tax_returns/serializers.py
- income_tax_returns/urls.py
feat: add Section80CDocuments model and file handling for Section 80C including upload and delete functionality
> feat: add Section80CDocuments model and file handling for Section 80C including upload and delete functionality

- income_tax_returns/serializers.py
- income_tax_returns/tax_paid_details_views.py
feat: enhance error handling and response structure in TaxPaidDetails  views
> feat: enhance error handling and response structure in TaxPaidDetails  views

- income_tax_returns/capital_gains_views.py
- income_tax_returns/models.py
- income_tax_returns/urls.py
feat: enhance delete functionality in capital gains views to support file type specification
> feat: enhance delete functionality in capital gains views to support file type specification

- gst/helpers.py
- gst/models.py
- gst/serializers.py
- gst/urls.py
- gst/views.py
feat: enhance business and registration models with file upload paths and new fields
> feat: enhance business and registration models with file upload paths and new fields

- income_tax_returns/capital_gains_views.py
feat: add delete functionality for capital gains properties with file  handling support
> feat: add delete functionality for capital gains properties with file  handling support

- income_tax_returns/helpers.py
- income_tax_returns/models.py
- income_tax_returns/serializers.py
feat: refactor income details models and serializers to improve structure and add OtherIncomeDetailsInfo
> feat: refactor income details models and serializers to improve structure and add OtherIncomeDetailsInfo

- income_tax_returns/business_professional_income_views.py
- income_tax_returns/dividend_views.py
- income_tax_returns/family_pension_views.py
- income_tax_returns/foreign_income_views.py
- income_tax_returns/gift_income_views.py
- income_tax_returns/helpers.py
- income_tax_returns/house_property_income_views.py
- income_tax_returns/interest_income_views.py
- income_tax_returns/models.py
- income_tax_returns/other_capital_gains_views.py
- income_tax_returns/other_income_views.py
- income_tax_returns/serializers.py
- income_tax_returns/winning_income_views.py
feat: refactor upsert logic in business professional income views and  enhance response data structure
> feat: refactor upsert logic in business professional income views and  enhance response data structure

- income_tax_returns/business_professional_income_views.py
- income_tax_returns/other_capital_gains_views.py
- income_tax_returns/other_income_views.py
feat: enhance error handling and refactor instance retrieval in income views
> feat: enhance error handling and refactor instance retrieval in income views

- income_tax_returns/business_professional_income_views.py
- income_tax_returns/helpers.py
feat: update references in business professional income views and helpers for consistency
> feat: update references in business professional income views and helpers for consistency

- income_tax_returns/helpers.py
- income_tax_returns/models.py
- income_tax_returns/views.py
feat: add draft filing certificate upload path and enhance review status options
> feat: add draft filing certificate upload path and enhance review status options

- income_tax_returns/capital_gains_views.py
- income_tax_returns/urls.py
fix: update URL pattern for equity mutual fund file deletion to include 'files' in path
> fix: update URL pattern for equity mutual fund file deletion to include 'files' in path

- income_tax_returns/agriculture_income.py
- income_tax_returns/serializers.py
- labour_license/helpers.py
- labour_license/models.py
- labour_license/serializers.py
- labour_license/urls.py
- labour_license/views.py
- trade_license/helpers.py
- trade_license/models.py
- trade_license/serializers.py
- trade_license/urls.py
- trade_license/views.py
feat: enhance service request handling with new endpoints and model updates
> feat: enhance service request handling with new endpoints and model updates

- payroll/views.py
fix: update employee ID key in earnings data retrieval
> fix: update employee ID key in earnings data retrieval

- servicetasks/models.py
fix: update status choices in ServiceSubTask model for clarity and consistency
> fix: update status choices in ServiceSubTask model for clarity and consistency

- income_tax_returns/other_capital_gains_views.py
fix: optimize data handling in other_capital_gains_views to avoid unnecessary copying when files are present
> fix: optimize data handling in other_capital_gains_views to avoid unnecessary copying when files are present

- usermanagement/other_factors.py
- usermanagement/urls.py
feat: add API endpoint to retrieve booked time slots by date
> feat: add API endpoint to retrieve booked time slots by date

- usermanagement/other_factors.py
> Remodifed The case as per 

- income_tax_returns/capital_gains_views.py
- income_tax_returns/other_income_views.py
fix: improve file handling in capital_gains_views and enhance error management in other_income_views
> fix: improve file handling in capital_gains_views and enhance error management in other_income_views

- usermanagement/create_service_request.py
fix: remove unnecessary blank line in create_service_request.py
> fix: remove unnecessary blank line in create_service_request.py

- invoicing/models.py
- invoicing/serializers.py
- msme_registration/models.py
- msme_registration/urls.py
- msme_registration/views.py
- usermanagement/models.py
- usermanagement/serializers.py
fix: update models and serializers for MSME registration, enhance file handling, and add unique constraints
> fix: update models and serializers for MSME registration, enhance file handling, and add unique constraints

- msme_registration/helpers.py
- msme_registration/models.py
fix: add draft filing certificate upload path and enhance review status choices in models
> fix: add draft filing certificate upload path and enhance review status choices in models

- invoicing/serializers.py
fix: add branches JSONField to CustomerProfileGetSerializers for branch data handling
> fix: add branches JSONField to CustomerProfileGetSerializers for branch data handling

- msme_registration/serializers.py
fix: update RegisteredAddressSerializer to include location_of_plant_or_unit field
> fix: update RegisteredAddressSerializer to include location_of_plant_or_unit field

- invoicing/serializers.py
fix: make branch_code required and add customer_branch field to serializers
> fix: make branch_code required and add customer_branch field to serializers

- usermanagement/views.py
**fix: remove redundant code in email existence check response**
> fix: remove redundant code in email existence check response

- scripts/stop_docker.sh
fix: add script to gracefully stop and remove Docker container
> fix: add script to gracefully stop and remove Docker container

- usermanagement/views.py
fix: update success message in happy_coder view for consistency****
> fix: update success message in happy_coder view for consistency

- usermanagement/views.py
> fix: update success message in happy_coder view for clarity

- usermanagement/add_team_business.py
- usermanagement/business_registration_api.py
- usermanagement/service_views.py
- usermanagement/standard_registration.py
- usermanagement/utils.py
fix: update is_active field to use boolean values for consistency
> fix: update is_active field to use boolean values for consistency

- appspec.yml
**fix: enable overwrite option in appspec.yml for deployment consistency**
> fix: enable overwrite option in appspec.yml for deployment consistency

- appspec.yml
- scripts/clean_instance.sh
fix: update appspec.yml to use clean_instance.sh for instance cleanup
> fix: update appspec.yml to use clean_instance.sh for instance cleanup

- Tara/settings/default.py
- Tara/utils.py
**feat: add custom exception handler for database integrity errors**
> feat: add custom exception handler for database integrity errors

- Tara/templates/salary_template.html
- payroll/serializers.py
- payroll/views.py
fix: optimize padding and line-height in salary template and improve salary calculations in serializers
> fix: optimize padding and line-height in salary template and improve salary calculations in serializers

- appspec.yml
- buildspec.yml
> remodified code

- usermanagement/views.py
**fix: correct spelling in success message response for happy_coder view**
> fix: correct spelling in success message response for happy_coder view

- usermanagement/views.py
fix: correct spelling error in success message of happy_coder view
> fix: correct spelling error in success message of happy_coder view

- usermanagement/views.py
remodified code as per new change
> remodified code as per new change

- payroll/bulk_employee_upload.py
- payroll/bulk_salary_details_upload.py
- payroll/generate_salary_upload_template.py
- payroll/urls.py
- payroll/views.py
feat: add bulk salary details upload functionality and enhance attendance generation logic
> feat: add bulk salary details upload functionality and enhance attendance generation logic

- usermanagement/views.py
feat: modify OTP email sending logic for special email addresses
> feat: modify OTP email sending logic for special email addresses

- payroll/views.py
fix: update PT enabled logic to check for existence of payroll PT details
> fix: update PT enabled logic to check for existence of payroll PT details

- payroll/views.py
fix: update deduction logic to check for EPF and ESI enabled status in statutory components
> fix: update deduction logic to check for EPF and ESI enabled status in statutory components

- invoicing/views.py
fix: update invoice filtering logic to include 'Partially Paid' status for better accuracy in payment tracking
> fix: update invoice filtering logic to include 'Partially Paid' status for better accuracy in payment tracking

- usermanagement/views.py
**feat: add additional special email addresses for OTP sending logic**
> feat: add additional special email addresses for OTP sending logic

- invoicing/views.py
- usermanagement/urls.py
- usermanagement/usage_limits.py
- usermanagement/views.py
Remodified The code as per The Module Usage Summary
> Remodified The code as per The Module Usage Summary

- docwallet/apps.py
- docwallet/helpers.py
- docwallet/urls.py
- docwallet/views.py
Added Documenet Wallet Quick search as per new Requirement
> Added Documenet Wallet Quick search as per new Requirement

- docwallet/helpers.py
- docwallet/models.py
> restructured the code

- docwallet/helpers.py
- docwallet/models.py
Restructed the lazy loading to solve the document wallet search
> Restructed the lazy loading to solve the document wallet search

- usermanagement/models.py
Refactor subscription cycle creation logic and improve error handling
> Refactor subscription cycle creation logic and improve error handling

- payroll/bulk_employee_upload.py
- payroll/views.py
- usermanagement/views.py
> Production Push 07-07-2025

- usermanagement/models.py
- usermanagement/views.py
Restruced The Subscription Plan case 07-07-2025
> Restruced The Subscription Plan case 07-07-2025

- usermanagement/models.py
Refactor subscription cycle creation for improved readability
> Refactor subscription cycle creation for improved readability

- usermanagement/views.py
Fix typo in success message of happy_coder view****
> Fix typo in success message of happy_coder view

- invoicing/views.py
- usermanagement/models.py
- usermanagement/other_factors.py
fix: update business field to OneToOneField and adjust context retrieval logic in invoicing profile
> fix: update business field to OneToOneField and adjust context retrieval logic in invoicing profile

- document_drafting/urls.py
fix: remove unused URL path for document fields and template
> fix: remove unused URL path for document fields and template

- payroll/bulk_salary_details_upload.py
- payroll/generate_salary_upload_template.py
- payroll/helpers.py
Remodified Bulk Upload case for Salary Template
> Remodified Bulk Upload case for Salary Template 

- payroll/serializers.py
- payroll/views.py
fix: update employee department count logic and enhance error message in department creation
> fix: update employee department count logic and enhance error message in department creation

- document_drafting/serializers.py
- document_drafting/urls.py
- document_drafting/views.py
- payroll/views.py
feat: add file field to ContextWiseEventAndDocument serializer and restore filtered documents by status view
> feat: add file field to ContextWiseEventAndDocument serializer and restore filtered documents by status view

- usermanagement/views.py
fix: update special email handling and change OTP recipient
> fix: update special email handling and change OTP recipient

- payroll/views.py
> new changes remodification

- payroll/views.py
new changes remodification rechanged th name
> new changes remodification rechanged th name

- document_drafting/helpers.py
refactor: remove date formatting functions and simplify context handling in PDF generation
> refactor: remove date formatting functions and simplify context handling in PDF generation

- payroll/bulk_employee_upload.py
Remodifed few cases and removed few fields
> Remodifed few cases and removed few fields

- payroll/generate_salary_upload_template.py
feat: integrate EarningsSerializer for improved earnings data handling in salary upload template
> feat: integrate EarningsSerializer for improved earnings data handling in salary upload template

- payroll/generate_salary_upload_template.py
- payroll/serializers.py
restructured the case and solved the bonus correction
> restructured the case and solved the bonus correction

- payroll/serializers.py
- payroll/urls.py
- payroll/views.py
Remodifed Bonus Incentive case as per New Cases That Got Changed****
> Remodifed Bonus Incentive case as per New Cases That Got Changed

- payroll/generate_salary_upload_template.py
- payroll/views.py
remodified the code for bulk upload case
> remodified the code for bulk upload case

- document_drafting/models.py
- payroll/views.py
feat: update event document status handling to ensure event_instance is set before marking as in_progress
> feat: update event document status handling to ensure event_instance is set before marking as in_progress

- payroll/generate_salary_upload_template.py
> remodified the code

- payroll/generate_salary_upload_template.py
Remodified code as per new Case
> Remodified code as per new Case

- payroll/views.py
restructured the entire code for slaary template
> restructured the entire code for slaary template

- payroll/views.py
> added income tax returns

- payroll/views.py
fix: update ESI and professional tax calculations to use basic monthly salary
> fix: update ESI and professional tax calculations to use basic monthly salary

- payroll/helpers.py
- payroll/serializers.py
- payroll/views.py
feat: add total bonus parameter to TDS calculation and improve account number validation
> feat: add total bonus parameter to TDS calculation and improve account number validation

- payroll/helpers.py
- payroll/views.py
feat: update TDS calculation to handle bonus or revisions and improve number formatting
> feat: update TDS calculation to handle bonus or revisions and improve number formatting

- payroll/views.py
fix: round monthly TDS calculation for improved accuracy
> fix: round monthly TDS calculation for improved accuracy

- docker-compose.yml
- nginx/http.conf
> remodifed 

- payroll/views.py
remodified the code and added the same in the bulk upload case as well
> remodified the code and added the same in the bulk upload case as well

- usermanagement/login_api.py
- usermanagement/models.py
- usermanagement/switch_context.py
feat: add legal_name to user and business context responses for improved clarity
> feat: add legal_name to user and business context responses for improved clarity

- payroll/bulk_employee_upload.py
Restructured the pf account number****
> Restructured the pf account number

- Tara/__init__.py
- Tara/scheduler_scripts/schedule_tasks.py
- Tara/settings/celery.py
- Tara/settings/default.py
- buildspec.yml
- docker-compose.yml
- document_drafting/tasks.py
- scripts/applicationstart.sh
testing celery in my development server****
> testing celery in my development server

- payroll/bulk_employee_upload.py
feat: add validation for pf_account_number, work_email, and mobile_number formats in bulk employee upload
> feat: add validation for pf_account_number, work_email, and mobile_number formats in bulk employee upload

- Tara/settings/default.py
- buildspec.yml
- docker-compose.yml
code push to test the celery cases
> cide push to test the celery cases

- Tara/settings/default.py
- requirements.txt
> Pushing the code to dev server

- Tara/scheduler_scripts/schedule_tasks.py
> code push to test new

- payroll/bulk_salary_details_upload.py
fix: correct typo in column name for monthly fixed allowance in bulk salary details upload
> fix: correct typo in column name for monthly fixed allowance in bulk salary details upload

- payroll/bulk_salary_details_upload.py
- payroll/views.py
fix: update component name for Professional Tax and correct deduction calculation in salary processing
> fix: update component name for Professional Tax and correct deduction calculation in salary processing

- payroll/urls.py
- payroll/views.py
refactor: optimize salary processing logic and include bonus incentives in net pay calculation
> refactor: optimize salary processing logic and include bonus incentives in net pay calculation

- payroll/services/salary_processor.py
- payroll/views.py
restructured the code as per new case
> restructured the code as per new case

- Tara/scheduler_scripts/salary_processing_payroll.py
**remodified the case as per new change to see**
> remodified the case as per new change to see

- Tara/templates/invoice.html
- invoicing/views.py
- payroll/attendance_controller.py
- payroll/employee_education.py
- payroll/employeecredentials.py
- payroll/face_recognition.py
- payroll/serializers.py
- payroll/views.py
fix: update response status codes in attendance and employee management APIs; improve invoice layout and formatting
> fix: update response status codes in attendance and employee management APIs; improve invoice layout and formatting

- Tara/templates/invoice.html
fix: adjust margins and font weights in invoice.html for improved layout and readability
> fix: adjust margins and font weights in invoice.html for improved layout and readability

- payroll/leavemanagement.py
- payroll/models.py
- payroll/serializers.py
- payroll/urls.py
Remodified Employee Leave balance set up as per change
> Remodified Employee Leave balance set up as per change

- payroll/models.py
change the Leave management code as per new case
> change the Leave management code as per new case

- payroll/leavemanagement.py
- payroll/urls.py
Added Leave Management Changes as poer new Cases
> Added Leave Management Changes as poer new Cases

- Tara/asgi.py
- Tara/consumer.py
- Tara/routing.py
- Tara/settings/default.py
- payroll/attendance_controller.py
- requirements.txt
Testing the redis and websockets
> Testing the redis and websockets

- Dockerfile
- requirements.txt
rechanged some cases to test websocket
> rechanged some cases to test websocket

- docker-compose.yml
> reverting back the old code

- Dockerfile
- docker-compose.yml
- requirements.txt
Testing The code again with new uvicorn case
> Testing The code again with new uvicorn case

- Dockerfile
> Production push 01-08-2025

- payroll/services/salary_processor.py
- payroll/views.py
feat: add previous month check for employee salary history retrieval in salary processing
> feat: add previous month check for employee salary history retrieval in salary processing

- payroll/employee_salary_details.py
feat: enhance employee salary details with structured earnings and deductions data for monthly and YTD calculations
> feat: enhance employee salary details with structured earnings and deductions data for monthly and YTD calculations

- Tara/templates/invoice.html
- invoicing/views.py
feat: update invoice layout; adjust margins and improve font styling for better readability
> feat: update invoice layout; adjust margins and improve font styling for better readability

- Tara/templates/invoice.html
- payroll/employee_salary_details.py
- payroll/generate_salary_upload_template.py
- payroll/urls.py
- payroll/views.py
feat: implement PF breakdown endpoint; restrict access to current and future months, and enhance invoice layout for better readability
> feat: implement PF breakdown endpoint; restrict access to current and future months, and enhance invoice layout for better readability

- Tara/templates/invoice.html
feat: enhance invoice layout; update text color for emphasis and improve padding for better readability
> feat: enhance invoice layout; update text color for emphasis and improve padding for better readability

- Dockerfile
- docker-compose.yml
code push to test the websockets
> code push to test the websockets

- payroll/views.py
fix: correct CTC calculation; change from division to floor division for accurate monthly values
> fix: correct CTC calculation; change from division to floor division for accurate monthly values

- payroll/views.py
> Production Push 08-08-2025

- Dockerfile
- docker-compose.yml
- payroll/views.py
- usermanagement/email_otp_request_service.py
Restructured the code and remodifed the websocket case
> Restructured the code and remodifed the websocket case

- docker-compose.yml
fix: update port mapping in docker-compose to use port 8001
> fix: update port mapping in docker-compose to use port 8001

- Tara/templates/invoice.html
- payroll/views.py
fix: update ESI contribution calculation; add esi_enabled parameter for conditional logic
> fix: update ESI contribution calculation; add esi_enabled parameter for conditional logic

- payroll/bulk_employee_upload.py
fix: update date parsing format in bulk employee upload; change from MM/DD/YYYY to DD-MM-YYYY
> fix: update date parsing format in bulk employee upload; change from MM/DD/YYYY to DD-MM-YYYY

- payroll/helpers.py
- payroll/serializers.py
- payroll/services/salary_processor.py
- payroll/views.py
feat: enhance employee serializers and views; rename PAN field, add bank details, and include NPS contribution
> feat: enhance employee serializers and views; rename PAN field, add bank details, and include NPS contribution

- payroll/services/salary_processor.py
- payroll/views.py
fix: update EPF calculation logic; incorporate employee contribution rate and enablement checks
> fix: update EPF calculation logic; incorporate employee contribution rate and enablement checks

- Tara/templates/invoice.html
fix: correct conditional check for order number in invoice template
> fix: correct conditional check for order number in invoice template

- docker-compose.yml
fix: update port mapping in docker-compose to use port 8000
> fix: update port mapping in docker-compose to use port 8000

- Dockerfile
> code push to dev 14-08-2025

- appspec.yml
- scripts/pull_images.sh
****Title:**
**feat:** add script to pull Docker images before installation and update application start process
**Description:**
This PR introduces a new script and updates the application startup flow for better reliability during deployments.
🔄 **Changes Made**
- Added scripts/pull_images.sh to pull backend and Redis images before installation.
- Updated scripts/applicationstart.sh to:
- Load environment variables from image_vars.env.
- Validate required variables (DOCKER_IMAGE, IMAGE_TAG, REDIS_IMAGE).
- Use pulled images to start containers with docker-compose.
- Ensure containers are launched cleanly without unnecessary rebuilds.
- Improved error handling and logging for better debugging.
✅ **Benefits**
- Prevents timeout errors during CodeDeploy startup by pulling images …
> feat: add script to pull Docker images before installation and update application start process

- payroll/attendance_controller.py
fix: correct response message for check-in in attendance controller
> fix: correct response message for check-in in attendance controller

- usermanagement/urls.py
- usermanagement/views.py
feat: add API endpoint for deleting Context objects
> feat: add API endpoint for deleting Context objects
